GET http://localhost:3000/posts
###

POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "Post 1",
  "content": "Bellingham >> Enzo Fernandez."
}

###

DELETE http://localhost:3000/posts/65251eae55f57c940b706877  
//place ID in the link and remove :id

###
GET http://localhost:3000/register

###

POST http://localhost:3000/register
Content-Type: application/json

{
  "name": "Lionel Messi",
  "email": "Messi@example.com",
  "password": "GOAT10"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "Messi@example.com",
  "password": "GOAT10"
}



